### Задание 1

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3, 3, 1],
     [6, 8, 11, 10, 7]])

In [3]:
print(A)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [4]:
print("Размерность A {}".format(A.ndim))


Размерность A 2


In [5]:
print("Форма A {}".format(A.shape))


Форма A (2, 5)


In [6]:
mean_a = A.mean(axis=1)
print("Средние значения строк: {}".format(mean_a))

Средние значения строк: [2.  8.4]


In [7]:
mean_a

array([2. , 8.4])

In [8]:
print("Размерность mean_a: {}".format(mean_a.ndim))

Размерность mean_a: 1


In [9]:
print("Средние значения столбцов: {}".format(A.mean(axis=0)))

Средние значения столбцов: [3.5 5.  7.  6.5 4. ]


### Задание 2

In [10]:
a_centered = np.subtract(A, np.transpose(np.vstack((mean_a, mean_a, mean_a, mean_a, mean_a))))
print("Вычитание: {}".format(a_centered))

Вычитание: [[-1.   0.   1.   1.  -1. ]
 [-2.4 -0.4  2.6  1.6 -1.4]]


### Задание 3

In [11]:
r1 = a_centered[0]
r2 = a_centered[1]
print(r1
print(r2)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


In [12]:
a_centered_sp = np.dot(r1, r2)
a_centered_sp

8.0

In [13]:
a_centered_sp/(a_centered.size - 1)

0.8888888888888888